[project]
name = "finance-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.128.8",
    "flask>=3.1.2",
    "langchain>=1.0.8",
    "langchain-anthropic>=1.2.0",
    "langgraph>=1.0.3",
    "pandas-ta>=0.4.71b0",
    "pydantic>=2.12.4",
    "pydantic-settings>=2.12.0",
    "python-dotenv>=1.2.1",
    "python-multipart>=0.0.22",
    "requests>=2.32.5",
    "uvicorn>=0.40.0",
    "yfinance>=0.2.66",
]
