"""create stock_metrics_history and stock_prices tables

Revision ID: 20d0770acb83
Revises: 
Create Date: 2026-03-11 16:05:16.339364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20d0770acb83'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_metrics_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('sector', sa.String(length=128), nullable=True),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('market_cap_cr', sa.Float(), nullable=True),
    sa.Column('pe', sa.Float(), nullable=True),
    sa.Column('pb', sa.Float(), nullable=True),
    sa.Column('roe', sa.Float(), nullable=True),
    sa.Column('roa', sa.Float(), nullable=True),
    sa.Column('net_margin', sa.Float(), nullable=True),
    sa.Column('debt_equity', sa.Float(), nullable=True),
    sa.Column('revenue_growth', sa.Float(), nullable=True),
    sa.Column('dividend_yield', sa.Float(), nullable=True),
    sa.Column('week52_high', sa.Float(), nullable=True),
    sa.Column('week52_low', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'snapshot_date', name='uq_metrics_symbol_date')
    )
    op.create_index('ix_metrics_symbol_date', 'stock_metrics_history', ['symbol', 'snapshot_date'], unique=False)
    op.create_index(op.f('ix_stock_metrics_history_snapshot_date'), 'stock_metrics_history', ['snapshot_date'], unique=False)
    op.create_index(op.f('ix_stock_metrics_history_symbol'), 'stock_metrics_history', ['symbol'], unique=False)
    op.create_table('stock_prices',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'date', name='uq_price_symbol_date')
    )
    op.create_index('ix_price_symbol_date', 'stock_prices', ['symbol', 'date'], unique=False)
    op.create_index(op.f('ix_stock_prices_date'), 'stock_prices', ['date'], unique=False)
    op.create_index(op.f('ix_stock_prices_symbol'), 'stock_prices', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_prices_symbol'), table_name='stock_prices')
    op.drop_index(op.f('ix_stock_prices_date'), table_name='stock_prices')
    op.drop_index('ix_price_symbol_date', table_name='stock_prices')
    op.drop_table('stock_prices')
    op.drop_index(op.f('ix_stock_metrics_history_symbol'), table_name='stock_metrics_history')
    op.drop_index(op.f('ix_stock_metrics_history_snapshot_date'), table_name='stock_metrics_history')
    op.drop_index('ix_metrics_symbol_date', table_name='stock_metrics_history')
    op.drop_table('stock_metrics_history')
    # ### end Alembic commands ###
